Updated the metrics for Persistence
ScalaConsultants/mesmer pull request #509
Opened 2022-09-17 09:16 UTC by guda249

Updated the Persistence metrics to the modified values.

Persistence modified metrics  from the application:
1. promexample_mesmer_akka_persistence_event_time_sum
2. promexample_mesmer_akka_persistence_event_time_count
3. promexample_mesmer_akka_persistence_event_time_bucket
4. promexample_mesmer_akka_persistence_recovery_time_sum
5. promexample_mesmer_akka_persistence_recovery_time_count
6. promexample_mesmer_akka_persistence_recovery_time_bucket

2022-09-26 12:31 UTC, lgajowy requested changes
Hi. Sorry for the late review - I was on vacation. Thanks for the contribution!

2022-09-26 12:31 UTC, lgajowy commented on example/docker/dashboards/akka-persistence.json
> +          "expr": "sum by($persistence_label)(rate(promexample_mesmer_akka_persistence_event_time_sum[1m]))",
(see above)

2022-09-26 12:31 UTC, lgajowy commented on example/docker/dashboards/akka-persistence.json
> +          "expr": "sum(rate(promexample_mesmer_akka_persistence_event_time_sum[$__rate_interval]))",
Similar story as above: `promexample_mesmer_akka_persistence_event_time_count` replaced `promexample_akka_persistence_persistent_event_total`

2022-09-26 12:31 UTC, lgajowy commented on example/docker/dashboards/akka-persistence.json
> +          "expr": "sum by($persistence_label)(rate(promexample_mesmer_akka_persistence_event_time_sum[$__rate_interval]))",
(as above)

2022-09-27 09:10 UTC, lgajowy commented
@guda249 The values presented in the dashboards do not make sense now, unfortunately (events do not take 5 hours for sure):

![Screenshot 2022-09-27 at 11 07 53](https://user-images.githubusercontent.com/1932045/192484596-ec2a8416-497b-4c89-ba3e-90c05e24204b.png)

It could be that I was wrong assuming we can use _sum histogram values. Or maybe some additional division is needed? Do you think you could investigate that?

2022-09-28 04:24 UTC, guda249 commented
@lgajowy  Sure, will look into this.

2022-10-10 16:48 UTC, guda249 commented
@lgajowy , I have looked into the metrics as the _sum metrics contains the sum of all time when that particular event has been triggered, couldn't find any proper division, which was giving meaningful graph. Except when i changed the graph timescale from ms to ns.

2022-10-17 09:04 UTC, lgajowy commented
@skipper1982 do you think you could take a look at this?

2022-10-17 09:35 UTC, skipper1982 commented
> @skipper1982 do you think you could take a look at this?

Sure. Will do.

2022-10-21 14:17 UTC, skipper1982 commented
@guda249: Please change the unit from `ms` to `ns`. And it should change ~5h into ~20ms, which seems about right.

2022-11-01 09:33 UTC, guda249 commented
Modifed the timeunit from ms to ns

2022-11-01 14:18 UTC, skipper1982 approved these changes
This looks great.

2022-11-02 10:52 UTC, lgajowy approved these changes

2022-11-02 10:52 UTC, merged

2022-11-02 10:52 UTC, lgajowy commented
Thanks!