Operator metrics
ScalaConsultants/mesmer pull request #638
Opened 2023-03-10 10:46 UTC by lgajowy

Closes #559 
___

## Summary:

Reinstates operator, demand, and processed messages metrics. Refactors the code a bit

2023-03-10 10:49 UTC, lgajowy commented
There's probably lots of code that could be refactored together with that pr but it would take too much time for one blow. So I decided to create this PR and any other cleanups/refactorings will be done in later phases (0.9.0 for example)

2023-03-13 10:22 UTC, ptrdom requested changes
Small nitpicks only. I cannot do more than a baseline code review - for me, this functionality just has too much code with too little context to be comprehended comfortably by a person that is not the author.

2023-03-13 10:22 UTC, ptrdom commented on otel-extension/src/main/scala/io/scalac/mesmer/otelextension/instrumentations/akka/stream/AkkaStreamMonitorExtension.scala
> +      val subStreamName = streamInfo.subStreamName
Unused variable.

2023-03-13 10:22 UTC, ptrdom commented on core/src/main/scala/io/scalac/mesmer/core/model/stream/ConnectionsIndexCache.scala
> +  def empty = new ConnectionsIndexCache(mutable.Map.empty)
Probably should not exist in main sources if it is only needed for testing.

2023-03-13 14:37 UTC, ptrdom approved these changes

2023-03-13 14:44 UTC, merged